---
os_family: "debian"
package_type: "deb"
package_manager: "apt"

# Repository configuratie
repositories:
  - apt-transport-https
  - software-properties-common
  - repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}] https://packages.microsoft.com/repos/code stable main"
    key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
    filename: vscode
  - repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}] http://archive.ubuntu.com/ubuntu noble universe"
    filename: universe
  - repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}] http://archive.ubuntu.com/ubuntu noble-updates universe"
    filename: universe-updates


# Repository applicaties
repository_apps_extra:
  - obs-studio

# Desktop packages
kde_packages:
  - kde-plasma-desktop
  - plasma-workspace
  - plasma-workspace-wayland
  - sddm
  - kde-standard

gnome_packages:
  - ubuntu-gnome-desktop
  - gnome-desktop
  - gnome-desktop-environment
  - gnome-shell
  - gnome-shell-extension-manager
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-top-icons-plus
  - gnome-shell-extension-dashtodock

# Development tools
development_packages_os_specific:
  - build-essential
  - chromium-browser
  - python3-dev
  - python3-full
  - python3-venv
  - flatpak

# Citrix dependencies
citrix_dependencies:
  - libwebkit2gtk-4.0-37
  - libgtk-3-0
  - libxml2
citrix_temp_file: "/tmp/citrix-workspace.deb"
# Python packages
python_packages:
  - molecule
  - pytest
  - yamllint
  - black
  - flake8
  - mypy
  - selenium

# Container group
container_group: podman

desktop_packages:
  - kde-plasma-desktop
  - sddm

# Applicaties die via script geïnstalleerd worden
ubuntu_script_apps:
  - name: Joplin
    url: https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh
    dest: /tmp/Joplin_install_and_update.sh
    mode: '0755'
    command: bash /tmp/Joplin_install_and_update.sh 